name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
      
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Sebelum"
          env
          source init
          export PATH=/home/ubuntu/.nvm/versions/node/v22.11.0/bin:$PATH
          echo "Setelah"
          env
          npm run test
